series: Basic C++
title:  Inheritance Slicing
author:
  name: 
  email: 
  github: https://github.com/IGME-RIT
description: An example demonstrating the concept of object slicing.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Pointer Casting
  - series: Basic C++
    title: References